
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/icons";
import { Footer } from "@/components/layout/footer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowRight, Bot, Target, Banknote } from "lucide-react";
import Image from 'next/image';

const features = [
    {
        icon: <Banknote className="h-8 w-8 text-primary" />,
        title: "Automated Allocations",
        description: "Set your rules once and watch your income get allocated automatically to savings, taxes, and more."
    },
    {
        icon: <Bot className="h-8 w-8 text-primary" />,
        title: "AI-Powered Plans",
        description: "Not sure where to start? Get a personalized allocation plan generated by AI based on your business type."
    },
    {
        icon: <Target className="h-8 w-8 text-primary" />,
        title: "Financial Goals",
        description: "Set and track goals for each of your accounts, from saving for a new laptop to building an emergency fund."
    }
]

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="container mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Logo className="size-7 text-primary" />
          <h1 className="text-xl font-semibold">Flow Bank</h1>
        </div>
        <nav className="flex items-center gap-2">
          <Button variant="ghost" asChild>
            <Link href="/blog">Blog</Link>
          </Button>
           <Button variant="ghost" asChild>
            <Link href="/faq">FAQ</Link>
          </Button>
           <Button variant="ghost" asChild>
            <Link href="/login">Sign In</Link>
          </Button>
           <Button asChild>
            <Link href="/signup">Get Started</Link>
          </Button>
        </nav>
      </header>
      <main className="flex-1">
        {/* Hero Section */}
        <section className="py-20 md:py-32">
            <div className="container mx-auto px-4 sm:px-6 text-center">
                <h2 className="text-4xl font-bold tracking-tight sm:text-6xl">
                    Effortless Income Allocation for Modern Businesses.
                </h2>
                <p className="mt-6 max-w-2xl mx-auto text-lg text-muted-foreground">
                    Flow Bank helps freelancers and small businesses automate their finances. Stop guessing, start allocating with purpose.
                </p>
                <div className="mt-10 flex justify-center gap-4">
                    <Button asChild size="lg">
                    <Link href="/signup">
                        Get Started Free
                        <ArrowRight className="ml-2" />
                    </Link>
                    </Button>
                </div>
                 <div className="mt-16 w-full max-w-4xl mx-auto">
                    <Card className="shadow-2xl">
                       <Image 
                        src="https://placehold.co/1200x600.png"
                        alt="Flow Bank Dashboard"
                        width={1200}
                        height={600}
                        className="rounded-t-lg"
                        data-ai-hint="app dashboard"
                        />
                        <div className="p-4 bg-muted/30 rounded-b-lg border-t text-sm text-muted-foreground text-left">
                            <p><strong>Pro Tip:</strong> Connect your bank account to automatically sync transactions and let our AI identify your income streams.</p>
                        </div>
                    </Card>
                 </div>
            </div>
        </section>

        {/* Features Section */}
        <section className="py-20 md:py-24 bg-card">
             <div className="container mx-auto px-4 sm:px-6">
                <div className="text-center mb-16">
                    <h3 className="text-3xl font-bold tracking-tight sm:text-4xl">Everything you need to manage your cash flow.</h3>
                    <p className="mt-4 max-w-xl mx-auto text-lg text-muted-foreground">Flow Bank is packed with features to help you succeed.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {features.map((feature, index) => (
                        <Card key={index} className="text-center p-8">
                            <div className="flex justify-center mb-4">
                                {feature.icon}
                            </div>
                            <h4 className="text-xl font-semibold mb-2">{feature.title}</h4>
                            <p className="text-muted-foreground">{feature.description}</p>
                        </Card>
                    ))}
                </div>
             </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
